package com.websource.ultra;
import android.app.*; import android.content.*; import android.net.Uri; import android.os.Bundle; import android.provider.MediaStore; import android.view.View; import android.widget.*;
import java.io.*; import java.net.*; import java.nio.charset.*; import java.text.SimpleDateFormat; import java.util.*; import java.util.concurrent.ExecutorService; import java.util.concurrent.Executors; import java.util.regex.*;
public class MainActivity extends Activity {
 private EditText urlInput; private Button fetchButton,copyButton,saveButton,shareButton; private ProgressBar progress; private TextView status,sourceView; private final ExecutorService executor=Executors.newSingleThreadExecutor(); private String currentSource="",currentUrl="",currentTitle="source";
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);urlInput=findViewById(R.id.urlInput);fetchButton=findViewById(R.id.fetchButton);copyButton=findViewById(R.id.copyButton);saveButton=findViewById(R.id.saveButton);shareButton=findViewById(R.id.shareButton);progress=findViewById(R.id.progress);status=findViewById(R.id.status);sourceView=findViewById(R.id.sourceView);fetchButton.setOnClickListener(v->fetchSource());copyButton.setOnClickListener(v->copyAll());saveButton.setOnClickListener(v->saveSource());shareButton.setOnClickListener(v->shareSource());Intent in=getIntent();if(in!=null&&Intent.ACTION_SEND.equals(in.getAction())&&in.getStringExtra(Intent.EXTRA_TEXT)!=null)urlInput.setText(in.getStringExtra(Intent.EXTRA_TEXT));}
 private void fetchSource(){String raw=urlInput.getText().toString().trim();if(raw.isEmpty()){Toast.makeText(this,"أدخل رابط الصفحة",Toast.LENGTH_SHORT).show();return;}if(!raw.matches("(?i)^https?://.*"))raw="https://"+raw;final String url=raw;setBusy(true,"جاري الاتصال بالخادم وجلب المصدر الأصلي...");executor.submit(()->{HttpURLConnection c=null;try{c=(HttpURLConnection)new URL(url).openConnection();c.setInstanceFollowRedirects(true);c.setConnectTimeout(20000);c.setReadTimeout(30000);c.setRequestMethod("GET");c.setRequestProperty("User-Agent","Mozilla/5.0 (Linux; Android 15) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0 Mobile Safari/537.36");c.setRequestProperty("Accept","text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8");c.setRequestProperty("Accept-Language","ar,en-US;q=0.9,en;q=0.8");c.setRequestProperty("Cache-Control","no-cache");int code=c.getResponseCode();InputStream is=code>=400?c.getErrorStream():c.getInputStream();if(is==null)throw new IOException("لا توجد استجابة نصية");byte[] data=readAll(is,25*1024*1024);Charset cs=detectCharset(c.getContentType(),data);String src=new String(data,cs),finalUrl=c.getURL().toString(),title=extractTitle(src);final String fsrc=src,furl=finalUrl,ftitle=title;runOnUiThread(()->{currentSource=fsrc;currentUrl=furl;currentTitle=ftitle;sourceView.setText(fsrc);status.setText("HTTP "+code+" • "+data.length+" bytes • "+cs.name()+" • "+furl);copyButton.setEnabled(true);saveButton.setEnabled(true);shareButton.setEnabled(true);setBusy(false,null);});}catch(Exception e){final String msg=e.getClass().getSimpleName()+": "+(e.getMessage()==null?"تعذر جلب المصدر":e.getMessage());runOnUiThread(()->{sourceView.setText("تعذر جلب View Source.\n\n"+msg);status.setText(msg);setBusy(false,null);});}finally{if(c!=null)c.disconnect();}});}
 private static byte[] readAll(InputStream in,int limit)throws IOException{ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[32768];int n,total=0;while((n=in.read(b))!=-1){total+=n;if(total>limit)throw new IOException("حجم المصدر تجاوز 25MB");out.write(b,0,n);}return out.toByteArray();}
 private static Charset detectCharset(String ct,byte[] d){if(ct!=null){Matcher m=Pattern.compile("(?i)charset\\s*=\\s*['\"]?([^; '\"]+)").matcher(ct);if(m.find())try{return Charset.forName(m.group(1));}catch(Exception ignored){}}int n=Math.min(d.length,8192);String head=new String(d,0,n,StandardCharsets.ISO_8859_1);Matcher m=Pattern.compile("(?i)<meta[^>]+charset\\s*=\\s*['\"]?([^\\s'\"/>;]+)").matcher(head);if(m.find())try{return Charset.forName(m.group(1));}catch(Exception ignored){}m=Pattern.compile("(?i)<meta[^>]+content=['\"][^'\"]*charset=([^'\"; ]+)").matcher(head);if(m.find())try{return Charset.forName(m.group(1));}catch(Exception ignored){}return StandardCharsets.UTF_8;}
 private static String extractTitle(String s){Matcher m=Pattern.compile("(?is)<title[^>]*>(.*?)</title>").matcher(s);if(m.find())return sanitize(m.group(1).replaceAll("<[^>]+>","").trim());return "source";} private static String sanitize(String s){s=s.replaceAll("[\\\\/:*?\"<>|\\r\\n]+","_").trim();return s.isEmpty()?"source":(s.length()>60?s.substring(0,60):s);}
 private void copyAll(){((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("View Source",currentSource));Toast.makeText(this,"تم نسخ المصدر كاملًا",Toast.LENGTH_SHORT).show();}
 private void saveSource(){try{String stamp=new SimpleDateFormat("yyyyMMdd_HHmmss",Locale.US).format(new Date());ContentValues v=new ContentValues();v.put(MediaStore.Downloads.DISPLAY_NAME,currentTitle+"_"+stamp+".html");v.put(MediaStore.Downloads.MIME_TYPE,"text/html; charset=utf-8");v.put(MediaStore.Downloads.RELATIVE_PATH,"Download/ViewSourceUltra");Uri out=getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);if(out==null)throw new IOException("تعذر إنشاء الملف");try(OutputStream os=getContentResolver().openOutputStream(out,"w")){os.write(currentSource.getBytes(StandardCharsets.UTF_8));}Toast.makeText(this,"حُفظ في Downloads/ViewSourceUltra",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"تعذر الحفظ: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
 private void shareSource(){Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,currentSource.length()<=800000?currentSource:("View Source: "+currentUrl+"\n\nالمصدر كبير؛ احفظه من التطبيق."));startActivity(Intent.createChooser(i,"مشاركة View Source"));}
 private void setBusy(boolean busy,String msg){fetchButton.setEnabled(!busy);urlInput.setEnabled(!busy);progress.setVisibility(busy?View.VISIBLE:View.GONE);if(msg!=null)status.setText(msg);} @Override protected void onDestroy(){executor.shutdownNow();super.onDestroy();}
}
